### ISSUE TITLE
Not Organize

### ISSUE THREAD

**Issue by AizuddinMuhaldin** [hajimohammadzaim/CO5027_BTS_ASG#5]
The placement of the content in some page is not organize

**Comment by hajimohammadzaim** [comment]
sorry not accepted your comment because sir razi give us until 30 april..

**Comment by hajimohammadzaim** [comment]
but it depending on what browser you use, either IE or google chrome..
clear History and try again...

again, sorry not accepted your comment because sir razi give us until 30 april..

thnk you for your comment
